### ISSUE TITLE
 Specify7 DwC-A validation issue

### ISSUE THREAD

**Issue by timrobertson100** [gbif/gbif-data-validator#56] opened 2017-10-24 19:03 UTC
A [DwC-A from Specify 7](http://preview.specifycloud.org/static/depository/dwca_export_2017-10-24T13:32:38.285479.zip) fails to validate showing "The file could not be processed, or it may be missing if you provided a URL.” while [it works on the previous validator](https://tools.gbif.org/dwca-reports/297-2517063343212606963.html)

**Comment by cgendreau** [comment] 2017-10-24 19:25
Never realized this was valid (multiple locations for a single `rowType` even if the tag is called `files`) therefore it will not validate.

```
<extension fieldsEnclosedBy="&quot;" fieldsTerminatedBy="," linesTerminatedBy="\r\n" rowType="http://rs.tdwg.org/ac/terms/Multimedia">
  <files>
    <location>collectionobjectattachment.csv</location>
    <location>researchworkattachment.csv</location>
  </files>
```

**Comment by timrobertson100** [comment] 2017-10-24 19:28
Yes it is valid [according the DwC Archive format](http://rs.tdwg.org/dwc/terms/guides/text/index.htm#files) but is not something I've ever seen in use.

**Comment by MattBlissett** [comment] 2018-12-19 12:50
Is this something that should be fixed? In which case, the issue is with dwca-io.

The original archive has gone.

**Comment by timrobertson100** [comment] 2018-12-19 12:55
It has always been part of the DwC-A spec (AKA [text guidelines](https://dwc.tdwg.org/text/) which I see now has some formatting issues @peterdesmet).

**Comment by MattBlissett** [comment] 2018-12-19 13:05
I'm closing this; if we ever intend to support these archives then the problem is with GBIF's interpretation (and eventually dwca-io).

**Closed as completed** 2018-12-19 13:04 UTC
